version: '3'

services:
  ebm-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

  ebm-app-new:
    build:
      context: ./app-new
      dockerfile: Dockerfile.idefic
    ports:
      - "5001:5001"  
    volumes:
      - ./app-new:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

