# Use the official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m nltk.downloader punkt stopwords wordnet

# Copy the Flask app files into the container
COPY . .

# Expose the port that the Flask app will run on
EXPOSE 5001

# Command to run the application
CMD ["flask", "--app", "app", "run"]

